### ISSUE TITLE
Minercraft does not support http connections to miners

### ISSUE THREAD

**Issue by Fletch153** [tonicpow/go-minercraft#16]
It would be great if it figured out whether the miner is using http or https depending on the URL or a flag.

**Comment by mrz1836** [comment]
I just added some basic support for this. Please re-open if something doesn't work for you guys ;-)

**Comment by Fletch153** [comment]
Awesome, that was quick!

Looking at the changes, Minecraft only supports either purely http miners or https, not a combination of both?

**Comment by mrz1836** [comment]
Not sure about a combination of both at the actual same time... But you could add/remove miners dynamically, thus replacing a miner config with `http` for `https` between each request etc...

Let me know - and we can adjust as needed

**Comment by mrz1836** [comment]
Starting with custom miners from the start:
https://github.com/tonicpow/go-minercraft/blob/master/examples/custom_miners/custom_miners.go

**Comment by mrz1836** [comment]
If you wanted multiple URL endpoints for each miner (IE failover, or different environments) - show me a suggested spec
