### ISSUE TITLE
Improved error message.

### ISSUE THREAD

**Issue by theflyingcodr** [tonicpow/go-minercraft#21]
**Is your feature request related to a problem? Please describe.**
At the moment if a mapi error is received as part of a request, minercraft will just check status code and then return an status x does not match y message.

This doesn't give us much to work with to understand the actual problem that occurred.

**Describe the solution you'd like**
Add the actual error from mapi to the error message.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mrz1836** [comment]
Closed with #22
