### ISSUE TITLE
BestQuote() fails upon bad response from a miner

### ISSUE THREAD

**Issue by Fletch153** [tonicpow/go-minercraft#5]
It's possible that if a miner has been incorrectly configured, or the API becomes unavailable that BestQuote() will not fall back to working API and will fail.

**Comment by mrz1836** [comment]
Thanks @Fletch153 

Feel free to submit a PR - I'll be circling back on this issue next week ;)

**Comment by Fletch153** [comment]
Cool thanks. I'll try to submit PRs where I can. In the meantime, I'll raise any issues I come across.
