### ISSUE TITLE
Updates for mAPI 1.5

### ISSUE THREAD

**Issue by theflyingcodr** [tonicpow/go-minercraft#78]
mAPI is getting updated very soon and there are some changes we will need to reflect here in terms of response formats and error codes.

These have all changed to give more detailed error responses and the concept of retryable vs non-retryable errors etc.

I don't yet have full detail of all changes but when I do I will update this ticket so the work can then be done to this lib to get it up  to date. This will probably be a new major version release for this lib as there are most likely breaking changes.

**Comment by mrz1836** [comment]
@theflyingcodr sounds like mAPI v2.0 lol

Let me know and we can roll out a new major version!

**Comment by theflyingcodr** [comment]
So had a good look through everything, i think we'll be good, main changes are:

* new 500 response code for internal mAPI issues, previously it returned a 400
* new 503 response code if the node is unavailable
* Submit Tx & Txs responses have a new `failureRetryable` field denoting if the tx can be resubmitted as it will have a chance of being processed
* Submit Tx &Txs responses have a new warnings array added which may include some node errors
* Txs already submitted will now return a success
* Some new error strings replacing the old constants
It may need a new version as we have to update the error constants, if you're relying on them in 1.4 and below they won't work if using the new constants. The new fields are backwards compatible, they'll just change to default values if not supplied.

Further details of the changes are https://github.com/bitcoin-sv-specs/brfc-merchantapi#enhancements and https://github.com/bitcoin-sv/merchantapi-reference#improvements

**Comment by theflyingcodr** [comment]
I'm working on a PR for this at the moment

**Comment by mrz1836** [comment]
PR #80 now closes this issue ;-)
