### ISSUE TITLE
Question regarding default miners

### ISSUE THREAD

**Issue by vitalibalashka** [tonicpow/go-minercraft#95]
Hi @mrz1836 . Currently there are 4 default known miners in go-minercraft.
But I've found that 2 of them(Mempool(https://www.ddpurse.com/openapi) and Matterpool(https://merchantapi.matterpool.io) are always unreachable. Matterpool is probably just completely shutten down. And it takes quite a long time to get any response from them.
Also TAAL requires auth_key since some time.
So could we delete mentioned 2 miners from KnownMiners const? And also could we update TAAL mAPI config with some public key(but to be honest I don't know if such key exist), I can't set up account on https://console.taal.com/

**Comment by mrz1836** [comment]
Good points @vitalibalashka.

I think for Mempool and matterpool, we can remove them for now and maybe leave them as suggestions.

The TAAL siutation is a little harder. I don't really like having a public key that everyone is using. I feel getting a TAAL key "shouldn't" be too hard 🤷

**Comment by vitalibalashka** [comment]
Hi @mrz1836. I've tried to set up an account this time and it was created. There were probably some problems on the TAAL side.
But, regarding tokens. Maybe it's not a good idea to commit any token to public repo. Probably it would be better to specify token by yourself in some configuration.
For example in case of bux, to specify token in bux-server configuration
